export { default as Navbar } from "@/components/Navbar/navbar";
export { default as Header } from "@/components/Hero/Hero3";
export { default as Featurestwo } from "@/components/features/index2";
export { default as FeatureSection } from "@/components/features/feature";
export { default as FAQnew } from "@/components/FAQ/new";
export { default as SecFooter } from "@/components/secfooter";
export { default as Footertwo } from "@/components/footer/index2";
export { default as TitleComponent } from "@/components/common/TitleComponent";
export { default as FeaturesBento } from "@/pages/BentoGrid/grid";
